name: release-docker

on:
  push:
    tags:
      - '*.*.*'
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Downcase repo
        run: echo REPOSITORY=ngosang/deluge-exporter >> $GITHUB_ENV
      -
        name: Docker metadata
        id: docker_metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REPOSITORY }},ghcr.io/${{ env.REPOSITORY }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
